### ISSUE TITLE
react-native-android-sms-listener does not work at all

### ISSUE THREAD

**Issue by ballsac** [andreyvital/react-native-android-sms-listener#34]
I generated a fresh app with `create-react-native-app`, followed the [installation instructions](https://github.com/CentaurWarchief/react-native-android-sms-listener#installation) for this package, and copy/pasted the [example code](https://github.com/CentaurWarchief/react-native-android-sms-listener#example), but it never worked.

I then tried code from the following issues to no avail:
https://github.com/CentaurWarchief/react-native-android-sms-listener/issues/28#issuecomment-355812842, https://github.com/CentaurWarchief/react-native-android-sms-listener/issues/31#issuecomment-394245981

Other things I tried:
- Using device simulator to simulate  receiving a text.
- Using a real device with `react-native run-android` and receiving an actual text.
- Generating a **signed APK** and installing it to my device.
- Adding `<uses-permission android:name="android.permission.RECEIVE_SMS" />` & `<uses-permission android:name="android.permission.READ_SMS" />` to AndroidManifest.xml

Here is my actual code:
```
import React from 'react';
import { StyleSheet, Text, View } from 'react-native';
import { PermissionsAndroid } from 'react-native';
import SmsListener from 'react-native-android-sms-listener';

export default class App extends React.Component {
  constructor() {
    super();
    this.SMSReadSubscription = {};
  }

  async requestReadSmsPermission() {
    try {
      var granted = await PermissionsAndroid.request(
        PermissionsAndroid.PERMISSIONS.READ_SMS, {
          title: 'Auto Verification OTP',
          message: 'need access to read sms, to verify OTP'
        }
      );
      if (granted === PermissionsAndroid.RESULTS.GRANTED) {
        alert('READ_SMS permissions granted', granted);
        console.log('READ_SMS permissions granted', granted);
        granted = await PermissionsAndroid.request(
          PermissionsAndroid.PERMISSIONS.RECEIVE_SMS, {
            title: 'Receive SMS',
            message: 'Need access to receive sms, to verify OTP'
          }
        );
        if (granted === PermissionsAndroid.RESULTS.GRANTED) {
          alert('RECEIVE_SMS permissions granted', granted);
          console.log('RECEIVE_SMS permissions granted', granted);
          SmsListener.addListener(message => {
            alert(message);
            console.log(message);
            //message.body will have the message.
            //message.originatingAddress will be the address.
          });
        } else {
          alert('RECEIVE_SMS permissions denied');
          console.log('RECEIVE_SMS permissions denied');
        }
      } else {
        alert('READ_SMS permissions denied');
        console.log('READ_SMS permissions denied');
      }
    } catch (err) {
      alert(err);
    }
  }

  componentDidMount() {
    this.requestReadSmsPermission();
  }

  render() {
    return (
      <View style={styles.container}>
        <Text>Open up App.js to start working on your app!</Text>
        <Text>Changes you make will automatically reload.</Text>
        <Text>Shake your phone to open the developer menu.</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
```

Tested with a SM-J727T.

**Comment by Ketn** [comment]
Don't call the listener within the requestReadSmsPermission() function.

Call it in componentDidMount, something like this:

```
componentDidMount() {
    this.requestReadSmsPermission();
    SmsListener.addListener(message => {
        alert(message);
        console.log(message);
    });
}
```

Should work.

**Comment by telmen** [comment]
@ballsac any update on this? Did it work?

**Comment by logesh-freshworks** [comment]
I tried it's not working


`/**
 * Sample React Native App
 * https://github.com/facebook/react-native
 *
 * @format
 * @flow
 */

import React, { Component } from 'react';
import { StyleSheet, Text, View, WebView } from 'react-native';
import SmsListener from 'react-native-android-sms-listener'
import { PermissionsAndroid } from "react-native";

async function requestReadSmsPermission() {
  try {
    const granted = await PermissionsAndroid.request(
      PermissionsAndroid.PERMISSIONS.READ_SMS,
      {
        title: "Auto Verification OTP",
        message: "need access to read sms, to verify OTP"
      }
    );
    if (granted === PermissionsAndroid.RESULTS.GRANTED) {
      console.log("sms read permissions granted", granted);
    } else {
      console.log("sms read permissions denied", denied);
    }
  } catch (err) {
    console.warn(err);
  }
}


export default class App extends Component {
  constructor(props) {
    super(props)
    this.SMSReadSubscription = {};
  }

  componentDidMount() {
    requestReadSmsPermission();
    console.log("sup dude");
    this.SMSReadSubscription = SmsListener.addListener(message => {
      console.log("Message:", message);
      //message.body will have the message.
      //message.originatingAddress will be the address.
    });
  }

  componentWillUnmount() {
    //remove listener
    this.SMSReadSubscription.remove();
  }

  render() {


    return (
      <View style={styles.container}>
        <Text>Hello There</Text>
      </View>
    );
  }
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#F5FCFF',
  }
});
`

**Comment by AE0011** [comment]
not woking in android 28

**Comment by Sylchauf** [comment]
it's working with the new permission

see https://github.com/CentaurWarchief/react-native-android-sms-listener/issues/31

**Comment by roshan9595** [comment]
> Don't call the listener within the requestReadSmsPermission() function.
> 
> Call it in componentDidMount, something like this:
> 
> ```
> componentDidMount() {
>     this.requestReadSmsPermission();
>     SmsListener.addListener(message => {
>         alert(message);
>         console.log(message);
>     });
> }
> ```
> 
> Should work.

@Ketn Can you please explain these?

**Comment by shubham2102** [comment]
Ask for READ_SMS as well as RECEIVE_SMS permission, it will work in sdk version 28.
